server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password: ''
  h2:
    console:
      enabled: 'true'
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics

info:
  app: Spring Boot 2 Essentials By DevDojo
  website: https://devdojo.academy

